### ISSUE TITLE
stars are used for the score but not shown in the result

### ISSUE THREAD

**Issue by individual-it** [piyush97/GoGitter#1]
in the battle you loose and win by the stars and followers ( https://github.com/piyush97/GoGitter/blob/2460930e8159a7304092efac014f517406d6c14f/app/utils/api.js#L30 ), but the stars are not shown in the result
Also the results do not show, why someone wins/looses

**Comment by piyush97** [comment]
Send me a screenshot where you can't see the stars and followers?
@individual-it

**Comment by individual-it** [comment]
![image](https://user-images.githubusercontent.com/2425577/57970421-d2ceb080-79a0-11e9-9271-9a89e4a58e3f.png)

**Comment by piyush97** [comment]
Stargazers can't be seen because of the limitations of GitHub API v2.
They're introduced in v3 which I'm not using as the app is open source and for beginners to learn react.
**V3 needs an API key.**

**Comment by piyush97** [comment]
![Screen Recording 2019-05-18 at 7 05 41 PM](https://user-images.githubusercontent.com/18229627/57970560-36a4a980-79a0-11e9-9635-ac9cf5443bd2.gif)
